import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
    <Header />
  
    <main className="flex">
    <p className="bg-gray-300">Hello</p>
    <p className="bg-pink-300">Hello</p>
    </main>
 
    </div>
  )
}
