import {getSession, useSession} from 'next-auth/react'
import Head from 'next/head'
import Header from '../components/Header'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'

export default function Home({ session }) {
   //const { data: session } = useSession()

  //if(!session) return <Login />

  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />

    <main className="flex">
      <Sidebar />

      <Feed />
    </main>

    </div>
  )
}

export const getServerSideProps = async (context)=>{
  const session = await getSession(context)

  return{
    props: { session }
  }
}
